# Generated by Django 2.2.6 on 2020-01-17 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200115_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('value', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('value', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='materialstate',
            index=models.Index(fields=['course_id'], name='core_materi_course__f8e861_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstate',
            index=models.Index(fields=['material_id'], name='core_materi_materia_39a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstate',
            index=models.Index(fields=['user'], name='core_materi_user_id_627f78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialstate',
            unique_together={('course_id', 'material_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='exercisecode',
            index=models.Index(fields=['course_id'], name='core_exerci_course__7d3269_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisecode',
            index=models.Index(fields=['material_id'], name='core_exerci_materia_6056ff_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisecode',
            index=models.Index(fields=['user'], name='core_exerci_user_id_f9e20c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisecode',
            unique_together={('course_id', 'material_id', 'user')},
        ),
    ]
