# Generated by Django 2.2.6 on 2020-01-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200117_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseCode',
            new_name='ExerciseState',
        ),
        migrations.RemoveIndex(
            model_name='exercisestate',
            name='core_exerci_course__7d3269_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisestate',
            name='core_exerci_materia_6056ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisestate',
            name='core_exerci_user_id_f9e20c_idx',
        ),
        migrations.AddIndex(
            model_name='exercisestate',
            index=models.Index(fields=['course_id'], name='core_exerci_course__36be1b_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisestate',
            index=models.Index(fields=['material_id'], name='core_exerci_materia_d154f4_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisestate',
            index=models.Index(fields=['user'], name='core_exerci_user_id_1d689e_idx'),
        ),
    ]
