# Generated by Django 2.2.6 on 2020-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstate',
            name='star',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialstate',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
