# Generated by Django 2.2.6 on 2020-02-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200122_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('file_path', models.TextField(blank=True, default='')),
                ('line', models.PositiveSmallIntegerField(default=0)),
                ('cursor', models.PositiveSmallIntegerField(default=0)),
                ('value', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exercisesnap',
            index=models.Index(fields=['course_id'], name='core_exerci_course__a96361_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesnap',
            index=models.Index(fields=['material_id'], name='core_exerci_materia_65a8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesnap',
            index=models.Index(fields=['user'], name='core_exerci_user_id_aaf0b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesnap',
            unique_together={('course_id', 'material_id', 'user')},
        ),
    ]
