# Generated by Django 2.2.6 on 2020-02-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200203_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSnapBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('snaps', models.TextField(blank=True, default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseSnap',
        ),
        migrations.AddIndex(
            model_name='exercisesnapbundle',
            index=models.Index(fields=['course_id'], name='core_exerci_course__43c037_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesnapbundle',
            index=models.Index(fields=['material_id'], name='core_exerci_materia_a303ca_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesnapbundle',
            index=models.Index(fields=['user'], name='core_exerci_user_id_b74ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercisesnapbundle',
            unique_together={('course_id', 'material_id', 'user')},
        ),
    ]
