# Generated by Django 2.2.6 on 2020-02-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200203_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisesnapbundle',
            unique_together=set(),
        ),
    ]
