# Generated by Django 2.2.6 on 2020-02-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200203_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestate',
            name='edit_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercisestate',
            name='open_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
