# Generated by Django 2.2.6 on 2020-02-07 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200207_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLogBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('logs', models.TextField(blank=True, default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exerciselogbundle',
            index=models.Index(fields=['course_id'], name='core_exerci_course__bae5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselogbundle',
            index=models.Index(fields=['material_id'], name='core_exerci_materia_0bffe6_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselogbundle',
            index=models.Index(fields=['user'], name='core_exerci_user_id_48a84a_idx'),
        ),
    ]
