# Generated by Django 2.2.6 on 2020-02-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200207_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('exp_group_id', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='coursestate',
            index=models.Index(fields=['course_id'], name='core_course_course__7e998a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursestate',
            index=models.Index(fields=['user'], name='core_course_user_id_9f2252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursestate',
            unique_together={('course_id', 'user')},
        ),
    ]
