# Generated by Django 2.2.6 on 2020-02-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200214_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course_id', models.SlugField()),
                ('material_id', models.SlugField()),
                ('question_id', models.SlugField()),
                ('value', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['course_id'], name='core_survey_course__d0bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['material_id'], name='core_survey_materia_4201eb_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['user'], name='core_survey_user_id_209299_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('course_id', 'material_id', 'user')},
        ),
    ]
